mincheol11/kh14semi3

- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/NewFile.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/NewFile.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/member/NewFile.jsp
> JSP adimin 공용 폴더 생성

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/BoardController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/controller/ScheduleController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/BoardDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/ScheduleDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dto/BoardDto.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dto/ScheduleDto.java
- kh14semi3/src/main/java/com/kh/kh14semi3/interceptor/BoardOwnerInterceptor.java
- kh14semi3/src/main/java/com/kh/kh14semi3/interceptor/BoardViewsInterceptor.java
- kh14semi3/src/main/java/com/kh/kh14semi3/interceptor/ScheduleInterceptor.java
- kh14semi3/src/main/java/com/kh/kh14semi3/mapper/BoardMapper.java
- kh14semi3/src/main/java/com/kh/kh14semi3/mapper/ScheduleMapper.java
> board,schedule

- kh14semi3/src/main/java/com/kh/kh14semi3/dto/BoardDto.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dto/ScheduleDto.java
> boardDto,ScheduleDto

- kh14semi3/src/main/java/com/kh/kh14semi3/mapper/BoardMapper.java
- kh14semi3/src/main/java/com/kh/kh14semi3/mapper/ScheduleMapper.java
> boardMapper,ScheduleMapper

- kh14semi3/src/main/java/com/kh/kh14semi3/dto/MemberDto.java
- kh14semi3/src/main/java/com/kh/kh14semi3/mapper/MemberMapper.java
> MemberDto, MemberMapper 생성

- kh14semi3/src/main/java/com/kh/kh14semi3/mapper/MemberMapper.java
> MemberMapper 수정

- kh14semi3/src/main/java/com/kh/kh14semi3/error/TargetNotFoundException.java
> TargetNotFoundException

- kh14semi3/src/main/java/com/kh/kh14semi3/mapper/BoardDetailMapper.java
- kh14semi3/src/main/java/com/kh/kh14semi3/mapper/BoardListMapper.java
> board List,detail mapper

- kh14semi3/src/main/java/com/kh/kh14semi3/vo/PageVO.java
> pageVO 이름 수정

- kh14semi3/src/main/webapp/WEB-INF/views/lecture/list.jsp
> 강의 목록(lecture_list)+검색 JSP 생성

- kh14semi3/src/main/webapp/WEB-INF/views/lecture/list.jsp
> 강의 목록(lecture_list) JSP 수정

- kh14semi3/src/main/java/com/kh/kh14semi3/configuration/CustomFileUploadProperties.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/AttachmentDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dto/AttachmentDto.java
- kh14semi3/src/main/java/com/kh/kh14semi3/mapper/AttachmentMapper.java
- kh14semi3/src/main/java/com/kh/kh14semi3/service/AttachmentService.java
> attachment,configuration

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/BoardController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/controller/ScheduleController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/BoardDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/ScheduleDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/mapper/ScheduleDetailMapper.java
- kh14semi3/src/main/java/com/kh/kh14semi3/mapper/ScheduleListMapper.java
board,schedule  dao,mapper,controller
> board,schedule  dao,mapper,controller

- kh14semi3/src/main/java/com/kh/kh14semi3/service/AttachmentService.java
- kh14semi3/src/main/resources/application.properties
> application 수정

- kh14semi3/src/main/java/com/kh/kh14semi3/interceptor/BoardOwnerInterceptor.java
- kh14semi3/src/main/java/com/kh/kh14semi3/interceptor/BoardViewsInterceptor.java
- kh14semi3/src/main/java/com/kh/kh14semi3/interceptor/ScheduleInterceptor.java
> board,schedule interceptor

- kh14semi3/src/main/webapp/WEB-INF/views/lecture/gradeInsert.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/lecture/list.jsp
> 성적입력(gradeInsert) JSP 생성중

- kh14semi3/src/main/resources/application.properties
> 마지막 주석 없애기

- kh14semi3/src/main/java/com/kh/kh14semi3/dao/LectureDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dto/LectureDto.java
- kh14semi3/src/main/java/com/kh/kh14semi3/mapper/LectureMapper.java
강의(Lecture) Dao, Dto, Mapper 생성
> 강의(Lecture) Dao, Dto, Mapper 생성

- kh14semi3/src/main/java/com/kh/kh14semi3/dao/BoardDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dto/BoardDto.java
> board dao dto 수정

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule jsp

- kh14semi3/src/main/webapp/WEB-INF/views/board/list.jsp
> board list 수정

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/ScheduleController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/ScheduleDao.java
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule 게시판 완성 디자인 x

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule list 수정

- kh14semi3/pom.xml
- kh14semi3/src/main/java/com/kh/kh14semi3/controller/AdminDepartmentController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/AdminDepartmentDao.java
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/expand.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/list.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/template/header.jsp
> list 업그레이드

- kh14semi3/src/main/resources/static/editor/editor.js
- kh14semi3/src/main/webapp/WEB-INF/views/board/write.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/edit.jsp
editor.js 수정 , schedule 게시판 수정
> editor.js 수정 , schedule 게시판 수정

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
관리자만 schedule 게시판 등록,수정,삭제 할 수 있도록 수정
> 관리자만 schedule 게시판 등록,수정,삭제 할 수 있도록 수정

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
schedule 게시판 관리자만 등록 수정 삭제 가능하게 수정
> schedule 게시판 관리자만 등록 수정 삭제 가능하게 수정

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/AdminDepartmentController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/AdminDepartmentDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/AttachmentDao.java
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/list.jsp
AdminDepartment list, edit[get], edit[post], reduce,
객체 생성 및 화면 구현
> AdminDepartment list, edit[get], edit[post], reduce, 객체 생성 및 화면 구현

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule 게시판 디자인 시작

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule 목록  수정

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule 목록 수정

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule 게시판 수정

- kh14semi3/src/main/webapp/WEB-INF/views/template/scheduleNavigator.jsp
> scheduleNavigator 생성

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/ScheduleController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/ScheduleDao.java
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule 게시판  모달 기능 추가

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/ScheduleController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/ScheduleDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/vo/PageVO.java
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
pageVO 수정, schedule 게시판에 month 멀티페이지 기능 추가
> pageVO 수정, schedule 게시판에 month 멀티페이지 기능 추가

- kh14semi3/src/main/java/com/kh/kh14semi3/dao/BoardDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/ScheduleDao.java
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule 게시판 디자인 수정

- kh14semi3/src/main/webapp/WEB-INF/views/board/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule,board 게시판 수정

- kh14semi3/src/main/webapp/WEB-INF/views/board/list.jsp
> board게시판에 footer 추가

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/ScheduleController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/ScheduleDao.java
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule 게시판 디자인 99.99999% 완

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/AdminLectureController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/AdminLectureDao.java
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/expand.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/list.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/list.jsp
lecture list, add, edit, remove, detail  (dao,contraller, jsp) 생성완료
> lecture list, add, edit, remove, detail  (dao,contraller, jsp) 생성완료

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/AdminLectureController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/AdminLectureDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dto/LectureDto.java
- kh14semi3/src/main/java/com/kh/kh14semi3/mapper/LectureMapper.java
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/list.jsp
> lecture mapper, dto 수정

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/ScheduleController.java
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
schedule 등록,수정,삭제 할 시 팝업 생성 추가
> schedule 등록,수정,삭제 할 시 팝업 생성 추가

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/BoardController.java
- kh14semi3/src/main/webapp/WEB-INF/views/board/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/board/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/board/list.jsp
board 게시판에 수정,삭제,등록 버튼 팝업 메세지 기능 구현
> board 게시판에 수정,삭제,등록 버튼 팝업 메세지 기능 구현

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/AdminLectureController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/AdminDepartmentDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/AdminLectureDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/restcontroller/AdminLectureRestController.java
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/expand.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/list.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/list.jsp
> lecture add,edit 추가 수정

- kh14semi3/src/main/webapp/WEB-INF/views/board/list.jsp
> board 게시판 목록 디자인

- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/edit.jsp
> lecture add 수정

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule 게시판 디자인

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule 게시판 모달 디자인 수정

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/AdminDepartmentController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/controller/AdminLectureController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/AdminLectureDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/restcontroller/AdminLectureRestController.java
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/expand.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/list.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/list.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/template/header.jsp
> lecture add,edit update

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/ScheduleController.java
- kh14semi3/src/main/webapp/WEB-INF/views/board/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/home/main.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> 미리보기 화면 디자인 시작

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/AdminDepartmentController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/AdminDepartmentDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/restcontroller/AdminDepartmentRestController.java
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/list.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/add.jsp
department dto mapper admin 없는걸로 변경
> department dto mapper admin 없는걸로 변경

- kh14semi3/src/main/java/com/kh/kh14semi3/restcontroller/HomeRestController.java
- kh14semi3/src/main/webapp/WEB-INF/views/home/main.jsp
schedule,board 미리보기 구현 완료 (링크X)
> schedule,board 미리보기 구현 완료 (링크X)

- kh14semi3/src/main/webapp/WEB-INF/views/home/main.jsp
> schedule board 미리보기 디자인 수정

- kh14semi3/src/main/webapp/WEB-INF/views/home/main.jsp
학사정보 메인홈페이지 schedule,board 미리보기 디자인 수정
> 학사정보 메인홈페이지 schedule,board 미리보기 디자인 수정

- kh14semi3/src/main/webapp/WEB-INF/views/home/main.jsp
학사정보 메인홈페이지 schedule,board 게시판 미리보기 디자인 수정
> 학사정보 메인홈페이지 schedule,board 게시판 미리보기 디자인 수정

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/MemberController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/ScheduleDao.java
> schedule 수정

- kh14semi3/src/main/webapp/WEB-INF/views/home/main.jsp
학사정보 홈페이지 schedule 미리보기 디자인 수정
> 학사정보 홈페이지 schedule 미리보기 디자인 수정

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
> schedule detail 수정

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule 모달 디자인 수정

- kh14semi3/src/main/java/com/kh/kh14semi3/dao/AdminLectureDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/restcontroller/AdminLectureRestController.java
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/expand.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/list.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/list.jsp
department , lecture (add,edit) 오류 수정
> department , lecture (add,edit) 오류 수정

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/ScheduleController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/ScheduleDao.java
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list2.jsp
> schedule 게시판 디자인 수정중

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/ScheduleController.java
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule 게시판 달력 완성

- kh14semi3/src/main/resources/application.properties
> application 원상복구

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule 모달 오류 해결

- kh14semi3/src/main/java/com/kh/kh14semi3/advice/EmptyStringAdvice.java
- kh14semi3/src/main/java/com/kh/kh14semi3/controller/BoardController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/BoardDao.java
- kh14semi3/src/main/webapp/WEB-INF/views/board/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/board/list.jsp
> board 게시판 디자인 추가

- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/expand.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/list.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/add.jsp
> add,expand 버튼 수정

- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/edit.jsp
lecture add, edit lecture_name 수정
> lecture add, edit lecture_name 수정

- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/edit.jsp
> lecture add edit 수정

- kh14semi3/src/main/resources/static/css/commons.css
- kh14semi3/src/main/webapp/WEB-INF/views/board/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/lecture/gradeInsert.jsp
게시판 상세, 성적입력 페이지 footer.jsp 추가 / .kh-container 높이 설정 수정(commons.css)
> 게시판 상세, 성적입력 페이지 footer.jsp 추가 / .kh-container 높이 설정 수정(commons.css)

- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/edit.jsp
> detail , edit 수정

- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/list.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/list.jsp
> list container 수정

- kh14semi3/src/main/resources/static/css/commons.css
> commons.css table 디자인 수정

- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/add.jsp
> fail 문구 , placeholder 문구 변경

- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/edit.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/department/expand.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/edit.jsp
lecture , department edit expand detail 수정
> lecture , department edit expand detail 수정

- kh14semi3/src/main/webapp/WEB-INF/views/home/map.jsp
> map 검색기능 디자인 추가

- kh14semi3/src/main/webapp/WEB-INF/views/lecture/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/registration/list.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/registration/regist.jsp
> 수강신청registration 관련페이지 디자인 수정

- kh14semi3/src/main/webapp/WEB-INF/views/lecture/grade.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/lecture/list.jsp
학생,교수 강의lecture 관련 페이지  디자인 통일
> 학생,교수 강의lecture 관련 페이지  디자인 통일

- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/edit.jsp
> add, edit 업데이트

- kh14semi3/src/main/java/com/kh/kh14semi3/controller/BoardController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/controller/ScheduleController.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/BoardDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/dao/ScheduleDao.java
- kh14semi3/src/main/resources/static/editor/editor.js
> board 게시판 기능 조회수 기능 수정

- kh14semi3/src/main/webapp/WEB-INF/views/board/write.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> board,schdule 수정

- kh14semi3/src/main/webapp/WEB-INF/views/board/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
> board schedule 수정

- kh14semi3/src/main/webapp/WEB-INF/views/board/detail.jsp
> Mincheolwang

- kh14semi3/src/main/webapp/WEB-INF/views/board/detail.jsp
> board 게시판 수정

- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/edit.jsp
> lecture add ,edit 수정

- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/lecture/edit.jsp
> add edit 수정

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/add.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/list.jsp
> schedule add,list 수정

- kh14semi3/src/main/webapp/WEB-INF/views/admin/member/takeOff.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/admin/member/takeOn.jsp
> 휴학 및 복학 사유 작성 페이지오류 수정

- kh14semi3/src/main/webapp/WEB-INF/views/board/detail.jsp
> board detail 수정

- kh14semi3/src/main/webapp/WEB-INF/views/schedule/detail.jsp
- kh14semi3/src/main/webapp/WEB-INF/views/schedule/edit.jsp
> schedule 상세,수정 페이지 수정

- kh14semi3/src/main/java/com/kh/kh14semi3/dao/AdminDao.java
- kh14semi3/src/main/java/com/kh/kh14semi3/restcontroller/MemberRestController.java
- kh14semi3/src/main/webapp/WEB-INF/views/admin/member/joinR.jsp
> joinR 중복검사 추가
